apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-mvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-mvc
    spec:
      containers:
      - image: spring-6-rest-mvc:0.0.1-SNAPSHOT
        name: spring-6-rest-mvc
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: localmysql
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/jt_spring6_sect16_chap170_db
status: {}
