services:
  mysql:
    container_name: mysql-spring-6-jt
    image: mysql:8
    # for macs
    # platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: Galerien3?
      MYSQL_DATABASE: jt_spring6_sect16_chap170_db
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: restadmin
    #expose:
    #  - 3306
    ports:
      - 3308:3306

  mongo:
    container_name: mongo-spring-6-jt
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"

  auth-server:
    container_name: auth-server-spring-6-jt
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    expose:
      - 9000

  rest-mvc:
    container_name: rest-mvc-spring-6-jt
    image: spring-6-rest-mvc:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: localmysql
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server-spring-6-jt:9000
    expose:
      - 8080
    depends_on:
      - mysql
